### ISSUE TITLE
Not compatible EE 5.2.5

### ISSUE THREAD

**Issue by alexschwarz89** [acirtautas/oxid-module-internals#13]
Hello,

just wanted to mention that the module seems to be not compatible with an EE 5.2.5 or I am missing something. Copied the repo folder inside modules/ and activated it. Cache cleared before.

 ```Faulty component --> ac_module_internals_metadata
---------------------------------------------
oxSystemComponentException-oxException (time: 2015-11-09 11:14:19): [0]: EXCEPTION_SYSTEMCOMPONENT_CLASSNOTFOUND 
 Stack Trace: #0 /var/www/core/oxutilsobject.php(180): oxUtilsObject->_getObject('oxsystemcompone...', 0, Array)
#1 [internal function]: oxUtilsObject->oxNew('oxSystemCompone...')
#2 /var/www/core/oxfunctions.php(340): call_user_func_array(Array, Array)
#3 /var/www/core/oxutilsobject.php(170): oxNew('oxSystemCompone...')
#4 [internal function]: oxUtilsObject->oxNew('ac_module_inter...')
#5 /var/www/core/oxfunctions.php(340): call_user_func_array(Array, Array)
#6 /var/www/core/oxshopcontrol.php(482): oxNew('ac_module_inter...')
#7 /var/www/core/oxshopcontrol.php(349): oxShopControl->_initializeViewObject('ac_module_inter...', '', NULL, NULL)
#8 /var/www/core/oxshopcontrol.php(131): oxShopControl->_process('ac_module_inter...', '', NULL, NULL)
#9 /var/www/core/oxid.php(32): oxShopControl->start()
#10 /var/www/index.php(18): Oxid::run()
#11 /var/www/admin/index.php(19): require_once('/var/www/index....')
#12 {main}
```

**Comment by acirtautas** [comment]
Hello @alexschwarz89 

I installed fresh CE 4.9.5 (same code base as EE 5.2.5) and __oxid module internals__ module using composer and activation did not caused any problems.

This is the content of __composer.json__ file I used:

    {
        "require": {
            "composer/installers": "~1.0",
            "acirtautas/oxid-module-internals": "@dev"
        }
    }

**Comment by MantasVaitkunas** [comment]
Hi, just tried to activate this module on EE 5.2.5. No errors, module works.

**Comment by acirtautas** [comment]
Thanks @MantasVaitkunas

**Comment by acirtautas** [comment]
@alexschwarz89 would you be able to reproduce the problem on __CE 4.9.5__ ?

**Comment by keywan-ghadami-oxid** [comment]
i had no problems on EE 5.2.7

**Comment by iboargun** [comment]
I had the same issue on EE 5.2.8. somehow oxid doesn't take dash as seperator, so i had to rename module folder to oxid_module_internals and also renamed in metadata.php

> 
'files'        => array(
        'ac_module_internals_data_helper'   => 'oxid_module_internals/core/ac_module_internals_data_helper.php',
        'ac_module_internals_fix_helper'   => 'oxid_module_internals/core/ac_module_internals_fix_helper.php',
        'ac_module_internals_metadata' => 'oxid_module_internals/controllers/admin/ac_module_internals_metadata.php',
        'ac_module_internals_state'    => 'oxid_module_internals/controllers/admin/ac_module_internals_state.php',
        'ac_module_internals_utils'    => 'oxid_module_internals/controllers/admin/ac_module_internals_utils.php'
    ),
    'templates'    => array(
        'ac_module_internals_metadata.tpl' => 'oxid_module_internals/views/admin/tpl/ac_module_internals_metadata.tpl',
        'ac_module_internals_state.tpl'    => 'oxid_module_internals/views/admin/tpl/ac_module_internals_state.tpl',
        'ac_module_internals_utils.tpl'    => 'oxid_module_internals/views/admin/tpl/ac_module_internals_utils.tpl',
    )
