### ISSUE TITLE
Getting an exception on oxid 4.10.2 community edition

### ISSUE THREAD

**Issue by BogdanChayka** [acirtautas/oxid-module-internals#19]
`EXCEPTION_SYSTEMCOMPONENT_CLASSNOTFOUND

#0 /var/www/html/nalala/core/oxutilsobject.php(188): oxUtilsObject->_getObject('oxsystemcompone...', 0, Array)
#1 [internal function]: oxUtilsObject->oxNew('oxSystemCompone...')
#2 /var/www/html/nalala/core/oxfunctions.php(368): call_user_func_array(Array, Array)
#3 /var/www/html/nalala/core/oxutilsobject.php(178): oxNew('oxSystemCompone...')
#4 [internal function]: oxUtilsObject->oxNew('ac_module_inter...')
#5 /var/www/html/nalala/core/oxfunctions.php(368): call_user_func_array(Array, Array)
#6 /var/www/html/nalala/core/oxshopcontrol.php(404): oxNew('ac_module_inter...')
#7 /var/www/html/nalala/core/oxshopcontrol.php(346): oxShopControl->_initializeViewObject('ac_module_inter...', NULL, NULL, NULL)
#8 /var/www/html/nalala/modules/_d3modcfg/modules/controllers/d3_oxshopcontrol_modcfg_extension.php(149): oxShopControl->_process('ac_module_inter...', NULL, NULL, NULL)
#9 /var/www/html/nalala/core/oxshopcontrol.php(126): d3_oxshopcontrol_modcfg_extension->_process('ac_module_inter...', NULL, NULL, NULL)
#10 /var/www/html/nalala/modules/_d3modcfg/modules/controllers/d3_oxshopcontrol_modcfg_extension.php(63): oxShopControl->start(NULL, NULL, NULL, NULL)
#11 /var/www/html/nalala/core/oxid.php(40): d3_oxshopcontrol_modcfg_extension->start()
#12 /var/www/html/nalala/index.php(26): Oxid::run()
#13 /var/www/html/nalala/admin/index.php(27): require_once('/var/www/html/n...')
#14 {main};`

**Comment by keywan-ghadami-oxid** [comment]
Doen't look like an bug in the module, it seams the module it self needs some fix state. You can try to use oxid console fix:states. If that does not help maybe something is wrong with the installation of the module.
